{{- include "nvd-mirror.validateValues" . }}
{{- if or (empty .Values.database.existingSecret) (empty .Values.nvdApiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nvd-mirror.fullname" . }}
  labels:
    {{- include "nvd-mirror.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if empty .Values.database.existingSecret }}
  DATABASE_URL: {{ include "nvd-mirror.databaseUrl" . | quote }}
  {{- end }}
  {{- if empty .Values.nvdApiKey.existingSecret }}
  NVD_API_KEY: {{ .Values.nvdApiKey.value | quote }}
  {{- end }}
{{- end }}
